// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Projet_C_.Data;

#nullable disable

namespace Projet_C_.Migrations
{
    [DbContext(typeof(SchoolContext))]
    partial class SchoolContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("Projet_C_.Models.class_echange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("objet_demande")
                        .HasColumnType("INTEGER");

                    b.Property<int>("objet_propose")
                        .HasColumnType("INTEGER");

                    b.Property<float>("prix")
                        .HasColumnType("REAL");

                    b.Property<int>("quantite")
                        .HasColumnType("INTEGER");

                    b.Property<int>("type")
                        .HasColumnType("INTEGER");

                    b.Property<int>("utilisateur_proposant")
                        .HasColumnType("INTEGER");

                    b.Property<int>("utilisateur_receveur")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Echanges", (string)null);
                });

            modelBuilder.Entity("Projet_C_.Models.class_objet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("type_objet")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Objets", (string)null);
                });

            modelBuilder.Entity("Projet_C_.Models.class_utilisateur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("prenom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("pseudo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Utilisateurs", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
